language: php

env:
  - DB=mysql DB_HOST=mysql DB_DATABASE=testdb DB_USERNAME=root DB_PASSWORD=""

branches:
  only:
    - master
    - development

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

addons:
  hosts:
    - mysql

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

install:
    - composer self-update
    - composer install

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS testdb;" -uroot; fi

script: php vendor/bin/codecept run --debug

cache:
  directories:
    - $HOME/.composer/cache
